"use client";
import { FormEvent, useEffect, useState } from "react";
const API="http://34.87.172.133:8000/api";
type Zone={id:string;name:string;comment:string;private_zone:boolean;record_count:number}; type Record={id:string;name:string;type:string;value:string;ttl:number;routing_policy:string};
const links=["Dashboard","Hosted zones","Traffic policies","Health checks","Resolver","Profiles"];
async function call(path:string, init?:RequestInit){const r=await fetch(API+path,{credentials:"include",headers:{"Content-Type":"application/json"},...init});if(!r.ok)throw new Error((await r.json().catch(()=>({detail:"Request failed"}))).detail);return r.status===204?null:r.json()}
export default function App(){
 const [me,setMe]=useState<any>(),[email,setEmail]=useState("admin@example.com"),[view,setView]=useState("Hosted zones"),[zones,setZones]=useState<Zone[]>([]),[selected,setSelected]=useState<Zone>(),[records,setRecords]=useState<Record[]>([]),[q,setQ]=useState(""),[modal,setModal]=useState<"zone"|"record"|null>(null),[edit,setEdit]=useState<any>(),[notice,setNotice]=useState("");
 const toast=(s:string)=>{setNotice(s);setTimeout(()=>setNotice(""),3200)};
 const loadZones=()=>call(`/zones?q=${encodeURIComponent(q)}`).then(setZones).catch(()=>{}); const loadRecords=(z=selected)=>z&&call(`/zones/${z.id}/records`).then(setRecords).catch(e=>toast(e.message));
 useEffect(()=>{call("/auth/me").then(setMe).catch(()=>{})},[]); useEffect(()=>{if(me)loadZones()},[me,q]);
 if(!me)return <main className="login"><section><div className="aws">aws <i>⌣</i></div><h1>Sign in to Route 53</h1><p>Use any email address to enter this demonstration console.</p><form onSubmit={async e=>{e.preventDefault();setMe(await call("/auth/login",{method:"POST",body:JSON.stringify({email})}))}}><label>Email address<input value={email} onChange={e=>setEmail(e.target.value)} type="email" required/></label><button>Sign in</button></form></section></main>;
 const showZone=(z:Zone)=>{setSelected(z);setView("Records");loadRecords(z)};
 const save=async(e:FormEvent)=>{e.preventDefault();try{if(modal==="zone"){const d={name:edit.name,comment:edit.comment||"",private_zone:!!edit.private_zone};await call(edit.id?`/zones/${edit.id}`:"/zones",{method:edit.id?"PUT":"POST",body:JSON.stringify(d)});loadZones()}else{const d={name:edit.name,type:edit.type,value:edit.value,ttl:Number(edit.ttl),routing_policy:edit.routing_policy};await call(edit.id?`/records/${edit.id}`:`/zones/${selected!.id}/records`,{method:edit.id?"PUT":"POST",body:JSON.stringify(d)});loadRecords()}setModal(null);toast("Changes saved successfully")}catch(x:any){toast(x.message)}};
 const remove=async(kind:"zone"|"record",id:string)=>{if(!confirm(`Delete this ${kind}? This cannot be undone.`))return;await call(kind==="zone"?`/zones/${id}`:`/records/${id}`,{method:"DELETE"});if(kind==="zone"){setSelected(undefined);setView("Hosted zones");loadZones()}else loadRecords();toast(`${kind==="zone"?"Hosted zone":"Record"} deleted`)};
 return <div className="shell"><header><span className="aws">aws <i>⌣</i></span><span>Services</span><span className="search">⌕ Search</span><span className="right">◉ {me.email}　⌄</span><button className="signout" onClick={async()=>{await call("/auth/logout",{method:"POST"});setMe(null)}}>Sign out</button></header><aside><b>Route 53</b><small>DNS management</small>{links.map(x=><button key={x} className={view===x?"active":""} onClick={()=>{setView(x);if(x==="Hosted zones")setSelected(undefined)}}>{x}</button>)}</aside><main className="content">{notice&&<div className="toast">✓ {notice}</div>}{view==="Hosted zones"?<Zones zones={zones} q={q} setQ={setQ} newZone={()=>{setEdit({name:"",comment:"",private_zone:false});setModal("zone")}} show={showZone} edit={(z:Zone)=>{setEdit(z);setModal("zone")}} remove={(z:Zone)=>remove("zone",z.id)}/>:view==="Records"&&selected?<Records zone={selected} records={records} back={()=>{setView("Hosted zones");setSelected(undefined)}} newRecord={()=>{setEdit({name:selected.name,type:"A",value:"",ttl:300,routing_policy:"Simple"});setModal("record")}} edit={(r:Record)=>{setEdit(r);setModal("record")}} remove={(r:Record)=>remove("record",r.id)}/>:<Coming name={view}/>}</main>{modal&&<Modal kind={modal} value={edit} close={()=>setModal(null)} save={save} set={setEdit}/>}</div>
}
function Zones(p:any){return <><div className="crumb">Route 53 / Hosted zones</div><div className="title"><div><h1>Hosted zones</h1><p>A hosted zone is a container for records that define how you want to route traffic.</p></div><button onClick={p.newZone}>Create hosted zone</button></div><input className="filter" placeholder="Filter hosted zones" value={p.q} onChange={e=>p.setQ(e.target.value)}/><table><thead><tr><th>Hosted zone name</th><th>Type</th><th>Record count</th><th>Comment</th><th/></tr></thead><tbody>{p.zones.length?p.zones.map((z:Zone)=><tr key={z.id}><td><a onClick={()=>p.show(z)}>{z.name}</a></td><td>{z.private_zone?"Private hosted zone":"Public hosted zone"}</td><td>{z.record_count}</td><td>{z.comment||"—"}</td><td><button className="link" onClick={()=>p.edit(z)}>Edit</button><button className="danger" onClick={()=>p.remove(z)}>Delete</button></td></tr>):<tr><td colSpan={5} className="empty">No hosted zones found. Create one to start managing DNS.</td></tr>}</tbody></table></>}
function Records(p:any){const [filter,setFilter]=useState("");const rows=p.records.filter((r:Record)=>`${r.name} ${r.type} ${r.value}`.toLowerCase().includes(filter.toLowerCase()));return <><div className="crumb"><a onClick={p.back}>Hosted zones</a> / {p.zone.name}</div><div className="title"><div><h1>{p.zone.name}</h1><p>Hosted zone details and record management</p></div><button onClick={p.newRecord}>Create record</button></div><div className="zone-meta"><b>Hosted zone ID</b><code>{p.zone.id}</code><b>Type</b>{p.zone.private_zone?"Private":"Public"}</div><input className="filter" placeholder="Filter records" value={filter} onChange={e=>setFilter(e.target.value)}/><table><thead><tr><th>Record name</th><th>Type</th><th>Value/Route traffic to</th><th>TTL (seconds)</th><th>Routing policy</th><th/></tr></thead><tbody>{rows.length?rows.map((r:Record)=><tr key={r.id}><td>{r.name}</td><td><b>{r.type}</b></td><td className="value">{r.value}</td><td>{r.ttl}</td><td>{r.routing_policy}</td><td><button className="link" onClick={()=>p.edit(r)}>Edit</button><button className="danger" onClick={()=>p.remove(r)}>Delete</button></td></tr>):<tr><td colSpan={6} className="empty">No records found.</td></tr>}</tbody></table></>}
function Coming({name}:{name:string}){return <div className="coming"><h1>{name}</h1><p>This Route 53 feature is coming soon.</p></div>}
function Modal({kind,value,close,save,set}:any){const zone=kind==="zone";return <div className="overlay"><form className="modal" onSubmit={save}><div className="modalhead"><h2>{value.id?"Edit":"Create"} {zone?"hosted zone":"record"}</h2><button type="button" className="x" onClick={close}>×</button></div><label>{zone?"Domain name":"Record name"}<input value={value.name} onChange={e=>set({...value,name:e.target.value})} placeholder={zone?"example.com":"www.example.com."} required/></label>{zone?<><label>Comment <input value={value.comment} onChange={e=>set({...value,comment:e.target.value})}/></label><label className="check"><input type="checkbox" checked={value.private_zone} onChange={e=>set({...value,private_zone:e.target.checked})}/> Create a private hosted zone</label></>:<><div className="two"><label>Record type<select value={value.type} onChange={e=>set({...value,type:e.target.value})}>{["A","AAAA","CNAME","TXT","MX","NS","PTR","SRV","CAA"].map(x=><option key={x}>{x}</option>)}</select></label><label>TTL<input type="number" min="0" value={value.ttl} onChange={e=>set({...value,ttl:e.target.value})}/></label></div><label>Value<input value={value.value} onChange={e=>set({...value,value:e.target.value})} required/></label><label>Routing policy<select value={value.routing_policy} onChange={e=>set({...value,routing_policy:e.target.value})}><option>Simple</option><option>Weighted</option><option>Latency</option><option>Failover</option></select></label></>}<div className="actions"><button type="button" className="secondary" onClick={close}>Cancel</button><button>{value.id?"Save changes":"Create"}</button></div></form></div>}
